alias gs="git status"
alias gc="git commit -m "
alias gb="git branch"
alias ga="git add ."
alias go="git checkout"
alias gcl="git clone"
alias gl="git log"
alias gph="git push"
alias gpl="git pull"
alias grao="git remote add origin"
alias gpset="git push --set-upstream origin master"

alias hc="hexo clean"
alias hg="hexo g"
alias hd="hexo d"
alias hs="hexo s"
alias hp="hexo clean && hexo g && hexo d"

alias c="clear"